### ISSUE TITLE
Missing contributing and code of conduct files

### ISSUE THREAD

**Issue by jzonthemtn** [o19s/ubi#16]
The readme [references](https://github.com/o19s/ubi/blob/main/README.md?plain=1#L130) contributing and code of conduct files that do not exist.

* https://github.com/o19s/ubi/blob/main/CONTRIBUTING.md
* https://github.com/o19s/ubi/blob/main/code_of_conduct.md

**Comment by epugh** [comment]
Thanks for opening this up...    Part of me almost wants to skip fixing it till we figure out governance better, but since we reference it...
