### ISSUE TITLE
Way to "connect" UBI events with queries

### ISSUE THREAD

**Issue by jzonthemtn** [o19s/ubi#26]
Right now, we don't have an easy straightforward way to link events and queries. There isn't any "glue" other than the `query_id` that links the two and this might not be sufficient.

In https://github.com/opensearch-project/user-behavior-insights/issues/34 I want to capture the index(es) that were searched in the UBI queries index, but this might not be appropriate for all use-cases. A more granular approach is likely needed.

We should consider the addition of an `application` field that both queries and events can use to form this linking. The `application` can be provided in the query's `ext` block, and `application` can be used in the event schema. Having `application` on both would provide a low-level way to connect queries and events.

**Comment by epugh** [comment]
FYI: the `ext` block is the specific way we add UBI to OpenSearch JSON based query DSL .

**Comment by epugh** [comment]
Are you suggesting that we should have an explicit `application` field added to the [query_attributes](https://o19s.github.io/ubi/docs/html/1.1.0/query.request.schema.html#query_attributes) and [event_attributes](https://o19s.github.io/ubi/docs/html/1.1.0/event.schema.html#event_attributes)???

I can imagine that you would have a typeahead and a global search, and you would want to distingush between these two sources of queries, when generating personlaization inputs or implicit judgement etc...  

Is `application` the right word?   `source`?  `origin`???

**Comment by jzonthemtn** [comment]
Question for everyone - is `application` the most appropriate name for the field?

**Comment by alexeyrodriguez** [comment]
Something that can help with naming. What are possible values of `application`? Types of search experience/feature: `type-ahead` or `global-search`. Will it also be used to separate multiple shops that an Open Search installation is supporting? The last two types can also mix of course. Any other?

@epugh I suppose you mean adding it to queries, since events already has `application`.

**Comment by wrigleyDan** [comment]
If we already have the `application` field in the [events schema](https://github.com/o19s/ubi/blob/main/schema/1.1.0/event.schema.json#L9) I'd vote for that name.

At least if that does not have any other meaning in the events schema? It feels like a field that should be present for both schemas.

**Comment by epugh** [comment]
Thanks for feedback team.  I'm going to use `application` and try to provide some nicer examples in the spec...!

**Comment by jzonthemtn** [comment]
We should capture `application` from the `ext` in queries in the plugin, also. Care to write that issue in the plugin repo?

**Comment by epugh** [comment]
![image](https://github.com/user-attachments/assets/2bc5aa0c-f29f-403e-bad2-d9775444c517)

![image](https://github.com/user-attachments/assets/9a9da119-4498-43b0-a117-2fbf4559eeac)

Here is two examples of `application` being on events and queries.

**Comment by epugh** [comment]
> We should capture `application` from the `ext` in queries in the plugin, also. Care to write that issue in the plugin repo?

https://github.com/opensearch-project/user-behavior-insights/issues/40

**Comment by epugh** [comment]
This is now in the plugin, but not in the spec...

**Comment by epugh** [comment]
Applicaiton shipped in the 1.2 version fo the schema, so we can close this ticket.
